### ISSUE TITLE
docs/quickstart.md: some corrections undone

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#14]
Due to a revision of `docs/quickstart.md` in commit [bea5b4422](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/commit/bea5b44227fd97f4f024bdf0160748cd6b7e854a) some corrections made earlier are undone. See the inline comments in the commit.

**Comment by samuvack** [comment]
We will check this asap. Thanks for the improvements in the Tech Docs.

**Comment by xdxxxdx** [comment]
@ghsnd .

Just modified, please have look the latest update. 
Thanks

**Comment by ghsnd** [comment]
Thanks for the update!
