### ISSUE TITLE
docs/quickstart.md: Consuming an LDES: VersionMaterialiseProcessor not valid processor?

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#19]
At [Consuming an LDES](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/quickstart.md#consuming-an-ldes): when importing the flow file NiFi warns about the VersionMaterialiseProcessor: 

![image](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/assets/3070412/0afe4ae7-af74-4a37-baf9-738a857b94b3)

**Comment by xdxxxdx** [comment]
Hello @ghsnd 
Nice catch. this processor is an obsoleted one. Please modify the NIFI flow file to use an up-to-date processor:

```
 "type":"be.vlaanderen.informatievlaanderen.ldes.ldi.processors.VersionMaterialiseProcessor",
                   "bundle":{
                      "group":"be.vlaanderen.informatievlaanderen.ldes.ldi.nifi",
                      "artifact":"version-materialisation-processor",
                      "version":"0.0.1-SNAPSHOT"
                   },
```

Please kindly refer to this page for the latest processor model: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/demos/031.nifi-workbench-components/data/NiFi_Workbench_Components.json
