### ISSUE TITLE
Incorrect LDI host configuration

### ISSUE THREAD

**Issue by kkostov** [Informatievlaanderen/VSDS-Tech-Docs#37]
**Describe the BUG**
In the quick start, the LDI configuration uses the endpoint `endpoint: http://host.docker.internal:8080/mobility-hindrances`. The `host.docker.internal` is OS-specific and not always available depending if and how Docker desktop is installed. When it fails, it does so silently (unless one is looking at the docker container logs) and so it can be confusing for folks following the Quick Start for the first time.

Since the LDI orchestrator is part of the same docker service, this can be replaced with the name of the service e.g. `endpoint: http://ldio-workbench:8080/mobility-hindrances`

**Site link or Repository**
https://informatievlaanderen.github.io/VSDS-Tech-Docs/quickstart/Publish_LDES

**Comment by samuvack** [comment]
Hi @kkostov ,

Thank you for posting this recommendation/issue. I have changed this in the tech docs.
