### ISSUE TITLE
Linked data event stream repitition in docs/_introduction/linked_data.md

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#40]
The section [Basic concepts of linked data](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/_introduction/linked_data.md#basic-concepts-of-linked-data) contains, right below the figure, the text:

> Linked data event stream, Linked data event stream, Linked data event stream, Linked data event stream, Linked data event stream, Linked data event stream, Linked data event stream Visualization of an RDF (RDF 1.1 Primer (w3.org))

which is probably not intended.

**Comment by samuvack** [comment]
thanks
