### ISSUE TITLE
Broken link in _introduction/LDES_server.md

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#41]
In [Ingesting sources (HTTP in)](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/_introduction/LDES_server.md#ingesting-sources-http-in), the link in *"More information on the HTTP ingestion can be found [here](https://github.com/Informatievlaanderen/VSDS-LDESServer4J#example-http-ingest-fetch-configuration)."* points to a fragment that's not there.

**Comment by samuvack** [comment]
Thank you for posting this issue. We have corrected the wrong/broken link.
