### ISSUE TITLE
Typo in docs/_introduction/LDES_server.md

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#42]
In the chapter [Geospatial fragmentation](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/_introduction/LDES_server.md#geospatial-fragmentation) there is a typo in the sentence

> The number of tiles **if** 2^2n^

Also, the second `^` seems to be unnecessary.

**Comment by samuvack** [comment]
Thank you for reporting this issue. This incorrect layout of the equation has been adjusted to a nice Latex equation.
