### ISSUE TITLE
Broken link in docs/_introduction/LDES_server.md

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#43]
The first sentence of [Retention policy](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/main/docs/_introduction/LDES_server.md#retention-policy) has a link that doesn't point to an example:

> A [retention policy](https://github.com/Informatievlaanderen/VSDS-LDESServer4J#example-retention) determines how long data will be kept ...

**Comment by samuvack** [comment]
thanks
