### ISSUE TITLE
docs/_introduction/LDES_server.md: empty example Swagger API

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#45]
[This line](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/024139a0d6a8403baebb9e0cddacfd976e5fa7ad/docs/_introduction/LDES_server.md?plain=1#L686) and below: `swagger2.html` seems not to be included or empty...

**Comment by samuvack** [comment]
thanks!
