### ISSUE TITLE
docs/_introduction/Specification.md: dead link to Linked Data

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#46]
The link on [this line](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/024139a0d6a8403baebb9e0cddacfd976e5fa7ad/docs/_introduction/Specification.md?plain=1#L18) points to an unexisting URL.

**Comment by samuvack** [comment]
thanks
