### ISSUE TITLE
docs/_introduction/Specification.md: two different URLs to TREE spec

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-Tech-Docs#47]
In [this line](https://github.com/Informatievlaanderen/VSDS-Tech-Docs/blob/024139a0d6a8403baebb9e0cddacfd976e5fa7ad/docs/_introduction/Specification.md?plain=1#L20C1-L20C2) there are two different URLs to the TREE specification. It's best to just use https://w3id.org/tree/specification .

**Comment by samuvack** [comment]
Thanks for the help in clarifying the content in the tech docs. This has been adjusted.
